### ISSUE TITLE
Water temperature?

### ISSUE THREAD

**Issue by akx** [hendricius/the-bread-code#110]
The basic dough recipe doesn't mention anything about water temperature.

I've understood that dry yeast needs a certain temperature for it to activate?

**Comment by hendricius** [comment]
Sorry - I totally forgot to reply.

I suggest to use cold water in most cases. That slows down the whole process. Colder dough is also a little easier to work. Some people say cold fermented bread tastes better, but I do not have any scientific evidence to support this claim.

When you have little time and want to speed up things, use warm water.
