### ISSUE TITLE
Convection ovens?

### ISSUE THREAD

**Issue by akx** [hendricius/the-bread-code#112]
I happen to be lucky enough to have a convection oven -- maybe something should be said about lower temperatures and/or shorter times required in one?

**Comment by martinkirsche** [comment]
As far as I know using a convection oven to bake bread is not a good idea. I think this is because it will dry out the bread too fast so that it can‘t raise anymore. However I never tested how the bread turns out if I turn on the fan.

**Comment by hendricius** [comment]
Interesting. I think you should be fine, if you cover the bread in a cast iron pan, it should not be that different.

Did you try it? What were the results?

**Comment by akx** [comment]
It didn't raise that well, that much was certain, but I'm not sure whether it was my dough's fault or the oven's. :D

**Comment by nimbius** [comment]
A convection oven was helpful for normalizing baking times in high altitudes for me.  at sea level, i encountered problems with the top crust splitting from the base.

**Comment by istepaniuk** [comment]
My convection oven, a pretty standard BOSCH electric oven, clearly states in the user manual not to use the convection setting for bread baking.

**Comment by hendricius** [comment]
I'll close this for now. Feel free to add some more details later.

Based on my current knowledge using a combination of lava rocks, towels in boiling water creates the best results while baking. I will post more details here: https://github.com/hendricius/the-bread-code/pull/119
