### ISSUE TITLE
Brotgewürz recipe?

### ISSUE THREAD

**Issue by nimbius** [hendricius/the-bread-code#117]
I noticed the German standard loaf seems to be missing something familiar...
Do Germans really use Brotgewürz in the bread?  or is this just some weird thing American restaurants add?

**Comment by epochcoder** [comment]
My Austrian girlfriend uses it aswell, so definitely not an American thing ;-)

**Comment by hendricius** [comment]
Sorry - for my late reply. I've heard that people from the area of "Franken" do that. I have not done that too much myself. You can however buy "Brotgewürz" in almost all supermarkets.

**Comment by hendricius** [comment]
Feel free to re-open. Closing this for now.
