### ISSUE TITLE
First one ever 

### ISSUE THREAD

**Issue by nsantini** [hendricius/the-bread-code#123]
I got very inspired by your repo and tried it

Haven’t tasted it yet but I’m already proud of it

Thanks for sharing all these recipes and techniques 

![BE597BC1-71D8-4B46-954C-DCE00AD0660D](https://user-images.githubusercontent.com/438741/65378839-8ad6e600-dd12-11e9-9da0-8390f5fe8c92.jpeg)

**Comment by hendricius** [comment]
Pretty good for the first one. How did the crumb look like of the bread? Are you going to keep baking yourself?

**Comment by nsantini** [comment]
It was quite good, it could have been a bit "crunchier" tho, maybe a lil longer in the oven next time.
I will try again, and now that summer is coming (here in New Zealand), is going to be outdoor pizza oven time
