### ISSUE TITLE
Mother Dough very Wet on day 7

### ISSUE THREAD

**Issue by greggman** [hendricius/the-bread-code#126]
thanks so much for your bread instructions.

I'm trying to make the mother dough but I'm worried I'm doing it wrong.

I'm using whole grain wheat

![IMG_9804](https://user-images.githubusercontent.com/234804/67498353-3ed4e380-f6ba-11e9-90bd-41ce65296a48.jpg)

The first day it was fairly dry but I measured 100g flour + 100g water like the instructions say

![IMG_5849](https://user-images.githubusercontent.com/234804/67498449-70e64580-f6ba-11e9-8b23-1319c2df2a44.jpg)

The next day I transferred it to a larger jar and added 50g flour + 50g water. That night it expanded large and touched the plastic on top. I stirred it to let the air out and continued to add 50g flour + 50g water each day. This is what it looks like on day 7 (and days 4, 5, and 6)

![IMG_9801](https://user-images.githubusercontent.com/234804/67498628-b86cd180-f6ba-11e9-9656-963592ad707a.jpg)

You can see there are almost no bubbles. You can also see the high mark from day 2.5 on the side of the jar. My apartment is around 25c constantly

Here's an gif to show the constency of what I have

![ScreenFlow](https://user-images.githubusercontent.com/234804/67501057-907f6d00-f6be-11e9-9cfb-c25488ab2b2e.gif)

Any ideas? Did I mess up? Can it be saved? Thanks

**Comment by martinkirsche** [comment]
It’s s probably too wet to hold any bubbles. But this shouldn’t be a problem. Your dough has a nice color and got bubbles before so it is alive and can be used. You can always add more flour to get a better feeling of how active it is.

If you don’t plan to use it right now you can store it in the fridge. I store mine by mixing just a tablespoon with 50g flour and 50g water, let it rest about 3 hours (it should not be too active when you plan to store it). Right before I put it inside the fridge I add another 50g of flour. Having a dry dough will ensure that you can store it up to two weeks without killing it.

**Comment by vardaro** [comment]
When starting a new leaven, the starter will typically become very active within a few days of initial creation. Although it may look ready, it's not recommended to bake with it just yet. Following the initial highly active phase, the starter will stagnate for a few days and seem to be dead. Continue your feeding rhythm, once it begins to show activity it, it will be ready to bake with.

**Comment by hendricius** [comment]
Yep - closing as of now. Just keep going. I also noticed by starter becomes more bubbly with rye flour. Do let us know if it does not work.
