### ISSUE TITLE
Sourdough recipe strictness

### ISSUE THREAD

**Issue by nydn** [hendricius/the-bread-code#127]
So, on the 4th day of making my own sourdough, I've accidentally added 100g of water instead of 50g with 50g of flour. I was tired and wasn't paying attention and ...
Is it ruined?

It doesn't look that bad after 1 day, bubbles are forming though it looks a little bit dilute. Should I compensate with more flour next time?

**Comment by nydn** [comment]
On the next day, and there was some extra liquid aggregated on top, but overall it looked good under that  (or I should say it looked the same as the days before). 
So I removed the liquid from the top and added more flour this time (80g flour 50g water)

**Comment by vardaro** [comment]
No

The starter will just be soupy until you scoop out the mature starter and feed it again.
Regardless, the starter will be fine, just maintain your normal scheduling rhythm.

The liquid on top you are referring is called the hooch, which is byproduct alcohol produced during the fermentation process. It's generally an indication that the starter is hungry and requires feeding. You made the right call by scooping out the starter and doing another feeding.

I would not recommend tampering with the flour:water ratio, try to keep it consistent atleast during the developmental stages of the starter.

Anthony

**Comment by nydn** [comment]
Thanks for the thorough answer and the tips, will continue with the recommended values then :)
