### ISSUE TITLE
Basic dough bread feels like gluten free bread

### ISSUE THREAD

**Issue by coaxial** [hendricius/the-bread-code#128]
I followed the basic dough recipe and used "white flour" from Migros (Switzerland.) Flours have no types here, but "white" flour has 12% proteins which is what I understand type 550 to have.

The variations I did from the recipe: I let the dough sit for about 10 hours instead of 8, and then let it rest 1h instead of overnight in the fridge. I also used a KitchenAid to mix the dough in the second stretch and fold (not sure if that was a good idea). I didn't have any razor handy so I didn't score the bread before putting it in the oven. And the dough was *very* wet, so I didn't flip it because it would stick to my hands too much and, I worried, fall apart.

In the end, the bread is ok, it rose and looks decent, but it could have more bubbles. I think this is because mixing it with the KA was too much and it collapsed all the gas pockets.

What bothers me the most though is that it has the texture of gluten-free bread. It's rather powdery compared to regular bread.

Any ideas for improvement?

**Comment by vardaro** [comment]
Powdery texture is likely attributed to underdeveloped gluten.

Did you autolyse? I can attest that this step is critical in developing gluten in the dough. Even 25 minutes will make a difference. What was your hydration level? What was your flour blend?

It's possible you may have over-autolysed the dough. A high hydration dough, in a warm climate, can kickstart an accelerated fermentation which at some point will begin to degrade the gluten into a very wet, unworkable dough as you described above.

My other hypothesis is that the stand mixer may have been the culprit. You must very gentle with the dough in the stretch and fold phase, as you are trying to retain the gas produced by the yeast during fermentation within the dough and also not destroy the gluten.  The stand mixer may have overworked the gluten, and destroyed that gluten you worked hard to develop. I have no science to back this up though, just my own conjecture.

Anthony

**Comment by hendricius** [comment]
Hi there,

sorry it took me so long to respond. Everything that @vardaro said sounds right. Maybe you also used too little water?
