### ISSUE TITLE
basic starter discard?

### ISSUE THREAD

**Issue by theanalyst** [hendricius/the-bread-code#132]
the starter recipe calls for 100% hydration 100g flour & subseq. 50g addition for 6 more days, nothing about discards are mentioned, so you end up with 800g of starter in the end?

**Comment by hendricius** [comment]
@theanalyst great that you mention this. There are many discard starter recipes. I would take it and store it in a separate jar. Feel free to also adjust the guide.

I typically always have around 50 grams of flour, 50 grams of water and another 50 grams of starter in the jar. The rest I store in another jar and use it when making a very sour rye bread for instance. It smells bad before baking, but quite well after baking.

**Comment by theanalyst** [comment]
Sorry, so do you discard when building a starter (which is what I saw in many recipes) keeping the 1:1:1 ratio, as I expect you discard 50g everyday and use 50g starter + 50g flour + 50g water or is it adding 50g flour & water everyday on the existing sum?

**Comment by hendricius** [comment]
It depends. Sorry for that haha.

I always feed 1 flour:1 water ratio. But I might sometimes use 1 part sourdough, but sometimes also just 0.5 parts, or 0.1 parts. If I have my sourdough at room temperature for a couple of days, it ferments way faster. It sometimes starts to smell very gross. That's when I typically reduce the quantity of sourdough a little.

If I had it in the fridge before, it takes it way longer to double in size. I typically aim for it to double in size after 4 hours or so. Then I know it is very active. This is the exact level of activity you want to properly bulk ferment a loaf.  I baked for a year with my starter not being active enough. I can't stress enough how important an active starter is.

Hope this made sense, let me know if you have further questions. Happy to explain more.

**Comment by theanalyst** [comment]
Thanks for the response :) I'm still at day 8 of building a starter, I get around a 30% rise in 8 hours or so (it's cold in my apartment even near the heater), so I believe I need to do a few more feeds before it is ready to double. I do maintain a 1:x:x ratio usually 1:1:1 so far

**Comment by hendricius** [comment]
Not sure if you have access to rye flour, but it is dope for sourdough. It works very well. How cold is it in your flat? In my case I have around 20C in the flat. Try using warm water to speed up the process 👍

**Comment by dbrgn** [comment]
> I typically aim for it to double in size after 4 hours or so

This information would be *very* useful in the ["getting started" guide](https://github.com/hendricius/the-bread-code/blob/master/basics/sourdough.md). Should the rising of the dough be tracked somehow (e.g. by adding a marker)? Are there certain "levels of rising" that should be reached?

Also, I'm on day 8 right now and followed the instructions very precisely until yesterday. The liquid is never discarded during these 8 days, right? Yesterday the dough still looked like soup (a *lot* of liquid on top) so I left away the water and only fed it with flour. Today it looks a *bit* better, but definitely doesn't have as many bubbles as your picture of day 8.

**Comment by hendricius** [comment]
@dbrgn how has it been going with your starter so far? I can send you a small recipe on baking something with your discard starter if you are interested.

**Comment by dbrgn** [comment]
I discarded the whole starter, it never developed like it should and it started to smell bad. Always meant to try again, but so far I haven't.

I'd still be interested in answers to these questions :)

- Should the liquid ever be discarded during the first 8-10 days?
- Should parts of the starter be removed, or do you always add more mass to the starter?
- Should the rising of the dough be tracked somehow (e.g. by adding a marker)? Are there certain "levels of rising" that should be reached?

**Comment by hendricius** [comment]
@dbrgn sorry for my slow response again. 

1) The liquid should not be discarded. It contains a lot of bacteria/yeast
2) On day 2, you take 50 grams of the previous mixture and mix in a new jar with 50g of flour and 50g of water. The rest can be discarded, or stored in a jar in the fridge for later baking
3) Yep - tracking the rise is a good idea. I like to use a rubberband.

**Comment by hendricius** [comment]
Hope this helps. Closing for now. Feel free to reopen.

**Comment by dbrgn** [comment]
Thanks! I guess I'll give it another try soon 🙂
