### ISSUE TITLE
Would it make sense to add more tools?

### ISSUE THREAD

**Issue by moritzgloeckl** [hendricius/the-bread-code#140]
I really like this repo, great job! I've already baked a few breads off the guidelines here, and I would like to add three more tools to the tools section which may make a baker's life easier.

1. Rubber Spatula - https://commons.wikimedia.org/wiki/File:Silicon_Spatulas.JPG
2. Bench scraper - https://commons.wikimedia.org/w/index.php?search=scraper&title=Special%3ASearch&go=Go&ns0=1&ns6=1&ns12=1&ns14=1&ns100=1&ns106=1#/media/File:BenchScraper.JPG
3. Pizza Shovel / Pizza Peel - https://commons.wikimedia.org/wiki/File:Pizza_shovel_peel2.jpg

What do you think? Should I open a PR?

**Comment by hendricius** [comment]
Yes please! That sounds like a great idea!
