### ISSUE TITLE
Add some more information about kneading dough with high rye content

### ISSUE THREAD

**Issue by moritzgloeckl** [hendricius/the-bread-code#141]
Breads with a high rye content (>=80%) are much harder to knead than regular wheat dough, due to the inability of the rye to form long gluten strands. It keeps breaking and just forms this homogeneous mess without developing much gluten. I would like to add more information, especially to the Golden standard German bread and the Bavarian rye bread that kneading might be different and what to look out for when baking this type of bread. 

Would you think it's a good idea to have this?

**Comment by hendricius** [comment]
100% - I need to revamp the recipe :). I feel there is 2 categories, breads with high gluten content and breads without, like rye for instance. You don't have to knead at all, basically you just mix and then you are done :)
