### ISSUE TITLE
Confusion with Sourdough amonts

### ISSUE THREAD

**Issue by phuhl** [hendricius/the-bread-code#146]
Hi, great documentation on sougherdough bread.  My German golden standard bread came out fantastic and tasted just like Paderborner which I could not find in bakeries since I moved to the Aachen area.

I had a moment (or multiple) of confusion, though:
In the [Sourdough](https://github.com/hendricius/the-bread-code/blob/master/basics/sourdough.md)-section, the instructions are:
> A healthy formula is 40% sourdough for a rye bread/full grain bread. Assuming you would bake 500 grams of flour, you will need 200 grams of sourdough. The breads on the above picture have been baked with that ratio.

> Remove the mother dough from your fridge. **Take 200 grams of your mother dough** and place it in a large bowl in front of you. 

In all the other places, I found that one should take 100 grams of mother dough and feed it to be 310g, return 110g and use 200g. This spawned a little confusion. Maybe the section above needs a little cleanup.

A second thing was, that in your [video](https://www.youtube.com/watch?v=nsyjVa5SSQI) (which actually was very helpfull, maybe a link should be included in the [German standard](https://github.com/hendricius/the-bread-code/blob/master/recipes/sourdough/golden-standard-german-bread.md) section, eventhough the rye-wheat ratio is different) you describe how you let the freshly mixed starter sit 8h, then kned with new flour, let sit for 6h, form the bread, let sit for 24h in fridge. That is what I did (except, for the 24h at the end, I just did like 3h in the living room, but thats beside the point). On the [Basic Sour Dough](https://github.com/hendricius/the-bread-code/blob/master/basics/basic-sour-dough.md) page, the 24h wait after forming the bread is ommitted in the tldr:
>  1. Take mother dough out of the fridge
    2. Mix 100 grams from mother dough + 105 grams flour (preferably whole grain) + 105 grams warm water = 310 grams
    3. Let mix sit for ~ 8 hours (to accelerate process use warmer water)
    4. Return 100 grams back from the mix to the mother dough (in the fridge)
    5. In a new, large bowl mix and knead 500 grams of flour with 325 grams of water and 12 grams of salt
    6. Add the sour dough (~200 grams) to the new bowl
    7. Knead
    8. Wait ~4 hours (or longer for a stronger sour flavour) for the gluten to form
    9. Shape the dough (be gentle to keep air bubles in the dough)
    10. Preheat oven to 270 degrees Celsius (Add baking stone if you have one)
    11. Once the oven is heated: Place a baking tray filled with water on the bottom (the steam will help the bread rise). Decrease temperature to 230 degrees Celsius. Insert bread for 25 minutes
    12. After 25 minutes remove the baking tray with water and bake for another 20 minutes

As my bread turned out very much amazing, I guess I interpreted the steps right. Still, some clarifications might help newcommers ;)

Best from Aachen, stay healthy

**Comment by geeForceOne** [comment]
Funny, I just wanted just to ask the same question as @phuhl.

**Comment by hendricius** [comment]
I agree. I definitely need to upgrade this and make it clearer :-). I was thinking about also tossing out several recipes, just to make sure we keep focus. What do you think?

**Comment by geeForceOne** [comment]
Hi @hendricius 

First of all thanks again for all the effort you put in here. Much appreciated.
At the moment I'm using only the basic wheat and sourdough recipies, so for me it would be fine to remove the others. But I don't know for the others?

Then another question on sourdough. I used the mother the 3rd time after 7 days, took out some, doubled the dough, half back to mother and the other half i used for baking. 
However the third bread didn't "blow" like the other two I did before. Does that mean that my mother dough is about to die? Is there a way to know if the mother is still healthy? 

Best
Giuseppe

**Comment by hendricius** [comment]
@geeForceOne I have changed my strategy a lot here hehe. Please check out my recipe one more time: https://github.com/hendricius/the-bread-code/blob/master/recipes/sourdough/basic-sour-dough.md. I think it should answer most of the questions.
