### ISSUE TITLE
All subsection links in `basic-sour-dough.md` are broken

### ISSUE THREAD

**Issue by vladh** [hendricius/the-bread-code#155]
https://github.com/hendricius/the-bread-code/blob/master/basics/basic-sour-dough.md

Basically, there's no information to be found on the last 6 steps, which makes the recipe pretty much unusable. :(

Perhaps I missed something? In any case, the links should be fixed.

Thank you for making this repo!

**Comment by hendricius** [comment]
Fixed :-)
