### ISSUE TITLE
Fermentation table with fridge-fermentation timings

### ISSUE THREAD

**Issue by vigna** [hendricius/the-bread-code#159]
First of all, thank you so much for all this information. With your guidance I was able for the first time in my life to make sourdough bread successfully. And I'm a programmer, so I totally enjoy the approach (and the repo).

One thing that I would find useful is a table similar to http://table.the-bread-code.io/ for overnight fridge-fermentation timings. How much time outside, given the percentage of starter and temperature, and how much time inside?

Maybe that's something written elsewhere, or it is easily deductible from the table, but stating it clearly in written form somewhere would really help me (and probably others).

**Comment by hendricius** [comment]
Thanks. I totally agree. This would be super valuable. However it might also be hard, since it depends on your initial dough temperature, inoculation rate (how much starter you used) and how cold the fridge is. If I had a dedicated fridge this would be very interesting for sure!

**Comment by vardaro** [comment]
A rough-hand model I've successfully used for determining cold fermentation length is roughly 3-4x what you'd normally ferment on the counter for. A sourdough loaf I'd proof on the counter for 4 hours would be ready after 12 hours in the fridge (effectively overnight). Not necessarily a data-driven approach, but it just seems to work :)

As stated previously, there's a myriad of variables that contribute to fermentation length. Specifying cold ferment timings would be a complex undertaking.

**Comment by vigna** [comment]
Good point. But is there any kind of test you would suggest to apply to a loaf in the fridge to establish whether it is overfermenting?

**Comment by vardaro** [comment]
https://youtu.be/6oAfl1u0fIw

**Comment by vigna** [comment]
I know. Then you put it in the fridge. When do you take it out? You can't do the poke test when it's in the fridge—the dough is hard.

**Comment by vardaro** [comment]
Yeah,, it becomes tricky when the dough is stiff. However the poke is still relevant here. Ultimately, judging whether the loaf is ready comes down to what condition the dough was in before placing it in the fridge, and the general temperature of your fridge.

If you keep near freezing refrigerator, you're going to need the dough to be fairly active before placing it in the fridge. You can expect the fermentation rate to fall drastically in a cold fridge, so you need to compensate this with a lengthier bulk fermentation (perhaps 6 hours at room temp). When I bake, I prefer a short bulk fermentation and a longer proof. So a typical loaf would be about 4 hours bulk fermentation at room temp and 12-24 hours of proofing in the fridge at 38 F.  Hope that makes sense

**Comment by hendricius** [comment]
@hamx0r you can find the original model here: http://www.wraithnj.com/breadpics/rise_time_table/bread_model_bwraith.htm.  These days I never rely on timings, I just go by how the dough looks. Timings depend on so many parameters, starter readyness, temperature etc.
