### ISSUE TITLE
Yeast amount in basic bread recipe

### ISSUE THREAD

**Issue by civilu** [hendricius/the-bread-code#160]
The basic bread recipe says to use _"1 gram of dry yeast or 0.5% or 3 grams of fresh yeast (1.5%)"_ which does not work out relative to the amount of flour.

Which is correct, the quantities or the percentages?

My gut tells me it's the percentages since 1 gram of dry yeast per half a kilo of flour seems a bit on the low side.

**Comment by hendricius** [comment]
I adjusted it. I'd always recommend to go for little yeast and give the dough more time. The slow fermentation allows the flour to break down the moment it is coming into contact with water. It's a great hack :-)
