### ISSUE TITLE
Basic dough recipe doesn't say when to add the yeast

### ISSUE THREAD

**Issue by matteuan** [hendricius/the-bread-code#20]
The basic dough recipe [here](https://github.com/hendricius/the-bread-code/blob/master/basics/basic-dough.md) doesn't say when to add the yeast to the dough. I think this should be added after the Form the Gluten chapter. It would be interesting to have a proper chapter on that (fresh yeast, dried yeast, mixed with milk?)

**Comment by hendricius** [comment]
Oops. Good catch and find. Of course. You are perfectly right.

Milk, dried yeast, fresh yeast, oil. How do you think we should structure this? Should we maybe introduce an A/B testing section where we test fresh yeast vs. dry yeast? Oil vs. no Oil. However we can always only change one parameter at the time.

**Comment by hendricius** [comment]
I think we should work on a versus section. In there we always gather comparisons with only 1 parameter change. We can then bake the same bread once with oil, once without. Once with milk, once without. Then people can see right away how parameter changes influence the bake.

Should we have one post per comparison? See this for instance: https://www.instagram.com/p/BhERhlnDgdQ/?taken-by=the_bread_code. Here I compared 2 different scoring techniques.
