### ISSUE TITLE
Compilation time is too long

### ISSUE THREAD

**Issue by AdityaAnand1** [hendricius/the-bread-code#23]
Debugging takes forever :/

And now I have a house full of shitty bread.

**Comment by eirslett** [comment]
You can fetch prebuilt binaries at your local bakery, but I'm afraid their recipe is not open source.

**Comment by digitaldesigndj** [comment]
I agree, this a real concern. If you're looking to quickly grind up some XP, consider trying out some "quick bread" recipes. Biscuits are a great (and tasty) example. Alton Brown's show Good Eats has an excellent episode that might help you get started.

**Comment by hendricius** [comment]
Closing for now. Local bakery workaround is suggested.
