### ISSUE TITLE
Pizza dough?

### ISSUE THREAD

**Issue by adnanh** [hendricius/the-bread-code#26]
Would be nice to have pizza dough recipe.

**Comment by hendricius** [comment]
Definitely. I actually got started initially with pizza dough. Then decided to switch to bread as I can enjoy that every day. Will keep you posted when I published the recipe.

**Comment by hendricius** [comment]
Would you guys be interested in regular pizza dough, or also some iterations? Sourdough pizza dough could be interesting too as well. I am just a little worried that our repo becomes too complex. We right now have Yeast bread, Sourdough Bread and then another one Pizza? Or should we categorise pizza as "Others"?  There could be many other recipes in others in the future.

Feedback appreciated on what you think makes the most sense.

**Comment by coaxial** [comment]
Isn't pizza dough another form of bread dough, technically?

**Comment by hendricius** [comment]
I posted some of my preliminary pizzas here:

https://www.reddit.com/r/Pizza/comments/8huxdx/the_battle_of_the_pizza_doughs_same_parameters/

I need to iterate a little more on the recipe. It is not perfect yet. The moment I think it is good I will add it to the repo.

**Comment by adnanh** [comment]
Will try it, so far I have been making my pizza dough using minimum number of ingredients: flour, salt, sugar, yeast, baking powder and warm water. Can't wait to try your recipes and see what difference in the taste, structure etc some aditional ingredients bring in.

**Comment by clehene** [comment]
> Would you guys be interested in regular pizza dough, or also some iterations? Sourdough pizza dough could be interesting too as well.

It would be awesome to have the variations on the pizza dough. In particular I've heard the pizza sourdough is pretty good

>  I am just a little worried that our repo becomes too complex.
This should be solvable through info representation. Varitations and more advanced stuff could be separate from the main info. E.g. at the end of a document or in a separate file with the same name and `-advanced` appendix. etc.

**Comment by Kohach** [comment]
If you're interested in making pizza dough there is a very nice youtube video series on how to properly make pizza at home with a traditional oven.

https://www.youtube.com/watch?v=5h3uzIs4C2w&list=PLURsDaOr8hWV_M3AUhvpEwTcE9865Uwk1

He starts from scratch and details every step to master the pizza recipe by testing several configurations and parameters. Hope you'll enjoy this series!

**Comment by hendricius** [comment]
I moved the pizza dough to a new repository: https://github.com/hendricius/pizza-dough
