### ISSUE TITLE
Baking temperature

### ISSUE THREAD

**Issue by dimavs** [hendricius/the-bread-code#32]
Should it be 270 degree over the whole process? Sounds a bit high.

**Comment by cweagans** [comment]
And that's 270C, right?

**Comment by dimavs** [comment]
Yeah, should be around 500F

**Comment by hendricius** [comment]
Oh shoot. I should have written, 270 initially, then turn it down to 230 for baking. Basically max temperature to get it really warm, then take 230.

It would be nice also to do some measurements on the internals of the dough, then when temperature X has been reached it is ready.

**Comment by hendricius** [comment]
Thanks. Fixed.
