### ISSUE TITLE
The baguette is missing

### ISSUE THREAD

**Issue by rmeertens** [hendricius/the-bread-code#33]
Currently trying this recipe: http://paulhollywood.com/recipes/baguettes/

Will let you know how it went!

**Comment by akx** [comment]
Geez, that'll be one big baguette if it's still baking. 😅 

How'd it go?

**Comment by rmeertens** [comment]
Decided to turn the baguette into a garlic baguette... Was pretty good actually!

**Comment by hendricius** [comment]
Please feel free to add a recipe if you want :). Closing this for now. Thanks!
