### ISSUE TITLE
Day 3-7 water temp for sourdough

### ISSUE THREAD

**Issue by aktasonur** [hendricius/the-bread-code#37]
**Day 2:**
Add another 50 grams of flour and 50 grams of **warm** water.

**Day 3-7:** 
Add another 50 grams of flour and 50 grams of water. Stir everything.

Day 3-7 does not say anything about the temp of the water, should it be **warm** as Day 2 or from Day 3, the water should be at room temperature?

**Comment by themmes** [comment]
>The water you use daily should always be between 20° and 30° degrees celsius. That is the ideal temperature for the yeast and bacteria. If you want to take it slower while baking, you can use colder water in the future. That slows down the whole process.

Is what it says at `Day 1`, covering all future days.

**Comment by hendricius** [comment]
Yes, exactly. Always use the same water temperature. Didn't want to repeat this over all the steps.

Let me know if it works. Closing for now.
