### ISSUE TITLE
Hard bread

### ISSUE THREAD

**Issue by AntouanK** [hendricius/the-bread-code#40]
Hi there.

I tried the basic bread recipe, although I skipped the second "Stretch and Fold Part".
So basically I:
- mixed the ingredients
- waited 30 mins
- did "Form the gluten"
- waited ~4 hours
- did Stretch and Fold Part 1
- waited ~30 mins
- baked for 30 mins

The issues I saw were : 
- the dough at the end was a bit "watery" so it wasn't possible to shape at all. 
- the bread is very hard the next morning. Probably the hardest bread I ever ate. I need a ... chainsaw to cut it! Why is that? Is it the flour? or the fact that I didn't let it rest for more hours and stretch again?

Thanks for the guide :D

**Comment by sexybiggetje** [comment]
Trial and error :).
I think maybe you need a bit more yeast, and do stretch and fold. That usually does the trick.
Watery dough is hard to see from here. It should be stretchy and stringy not watery.

**Comment by AntouanK** [comment]
I'll probably take some photos/video next time, so I can see the difference.

I used some ( probably crappy ) grocery store yeast.
![screenshot_2018-04-30_11-54-14](https://user-images.githubusercontent.com/4569111/39424166-39cb8b80-4c6d-11e8-8cd2-2e18cf758b43.png)
I used one sachet. The whole sachet is 8g, so I suppose the contents are around 5g as the recipe says.

would it make a difference to go buy a better one?

**Comment by dimavs** [comment]
Dough is about patience :-). Baby can't be born in 4.5 month, the same with dough

**Comment by hendricius** [comment]
It could be that your yeast was dead. This happens from time to time. Do a test, take a bowl and put in 3 grams of yeast with some sugar and warm water. Does it get bubbly after 2 hours?

**Comment by hendricius** [comment]
We should probably have a list of common errors when baking and then add this to it? I think it's a common problem many people will face.

**Comment by AntouanK** [comment]
@hendricius I'll try that now. Thank you.

So the fact that the bread is very hard, means the yeast is bad?
Does the yeast have to be "fresh"? Where do you buy it from?
What does the yeast amount/quality affect?

**Comment by AntouanK** [comment]
https://en.wikipedia.org/wiki/Yeast#Baking

> When the dough is baked, the yeast dies and the air pockets "set", giving the baked product a soft and spongy texture. 

I mean the bread has "holes", so I guess that worked?

**Comment by AntouanK** [comment]
Just to help, photos of the bread today.

![img_20180430_145101](https://user-images.githubusercontent.com/4569111/39430599-2d42e354-4c86-11e8-9cc6-bcddd33bc977.jpg)
![img_20180430_145115](https://user-images.githubusercontent.com/4569111/39430602-2d6cdfa6-4c86-11e8-894f-19448109a42c.jpg)

It's very difficult to cut it though. The inside is ok.

**Comment by AntouanK** [comment]
Oven, hot air, 250C for 25mins ( I thought 270 is too high, so I lowered it and baked it slightly less time ).

I did try to add a pyrex with water underneath, but the water started boiling and it sounded like it would get messy, so I removed it within a few minutes.
Using less water might worked, not sure.

**Comment by cweagans** [comment]
You _want_ the water to boil. The steam will help keep the crust soft.

**Comment by AntouanK** [comment]
Yeah, I get that. 
But I don't know if the oven will have any issues with hot water being spilled everywhere inside.
Is there any risk of ... damaging anything? ( I'm renting the apartment )

**Comment by hendricius** [comment]
Well done. Bread looks much better. I usually use dry yeast, but you can also use fresh yeast. I didn't notice any difference in breads when baking.

It shouldn't get that messy as it will just create steam in the oven. It's like making a turkey or so, the steaminess will be similar. Every oven can handle that.

Remove the bowl of water after 50% baking time.

**Comment by cweagans** [comment]
>  Is there any risk of ... damaging anything? ( I'm renting the apartment )

Just don't spill it. You don't want water to hit the coils in the bottom of the oven. I've had some luck with a deep dish with not a lot of water in it (like a 9"x13" pan with ~.5" of water in the bottom).

**Comment by AntouanK** [comment]
Thanks for all the answers.

To recap, to make the bread soft, we need steam in the oven. Right?
The amount of yeast is irrelevant ( I mean I don't need to add more next time or something, correct? )

**Comment by AntouanK** [comment]
Yes, the default in the oven is "4D hot air" or some marketing crap like that. I think it uses the fan by default.
I'll try to use a setting without fan.

Thanks.
