### ISSUE TITLE
Liquid on mother dough after day 2

### ISSUE THREAD

**Issue by themmes** [hendricius/the-bread-code#41]
The liquid (as described last sentence of sourdough recipe) floating on the mother dough already at day 2, should I remove this liquid?

**Comment by themmes** [comment]
Please note, I am running Weckpot with 1:1 ratio to recipe and wheat flour (version Whole grain)

**Comment by hendricius** [comment]
Don't worry, just keep stirring in the flour as you planned. Maybe you can create a small PR later with this adjustment.

**Comment by hendricius** [comment]
Added. Please see: https://github.com/hendricius/the-bread-code/blob/master/basics/common-problems-faq.md#there-is-liquid-gathering-on-top-of-my-sourdough-starter-when-making-it
