### ISSUE TITLE
Deployment and containerisation

### ISSUE THREAD

**Issue by rjbaker** [hendricius/the-bread-code#42]
Are you considering adding a deployment guide, perhaps using a container of some kind?

![container](https://images-na.ssl-images-amazon.com/images/I/71Ao8skvRIL._SX522_.jpg "Bread")

**Comment by SimonKagstrom** [comment]
I think this is actually a good idea - how to best store it afterwards. I'm looking for a nice breadbox.

**Comment by hendricius** [comment]
Btw. to container your bake - you might want to consider using proofing boxes. At the same time a really good thing to do is proofing the bread in the fridge for 24 hours. You can reproduce the same environment.
