### ISSUE TITLE
salt level is outside EU spec.

### ISSUE THREAD

**Issue by nimbius** [hendricius/the-bread-code#49]
Per the EU salt reduction framework, bread should always less than 2% salt. Bread in DE is 1.6%.
https://ec.europa.eu/health/sites/health/files/nutrition_physical_activity/docs/salt_report1_en.pdf

the UK standard in keeping with the EU salt reduction framework is 1.5 to 1.6% of the total amount of flour.  Slovenia has achieved a standard of just 1% per 100g flour.

the 2% recommended in the basic recipe seems...excessive.

**Comment by hendricius** [comment]
Interestingly my fiancé is a huge opponent of too heavy salt. She always complains about too much salt. Myself I also don't like too salty. It's interesting that the 2% is above the threshold. The bread itself does not taste salty at all.

The 2% Salt is on the dry matter. Assuming you have 1000 grams of flour and you want to bake a yeast bread. Then you will add 20 grams of salt. Then you add another 700 ML of water and 10 grams of yeast. Which means the total product will weigh 1710 grams without the salt. That would be 20/1710 = 1.1% salt in total on the final product.

How valuable are those numbers if they don't consider the final product?

**Comment by nimbius** [comment]
Salt in bread I feel is pretty controversial.  For example, Canada once took the record for bread that was saltier than seawater, at 2.65%.  As of March, 73 per cent of breads sold in Canada surpassed Health Canada’s voluntary targets for sodium, and nearly a quarter exceeded recommended maximums.

Yet, without salt, proper gluten structure cannot form and the final product is indistinguishable from a particularly toothsome couch cushion.  it also contributes to the maillard colouring of the crust and even its final texture as the gluten enters rest stages during cooling up to a day after baking.

Although I cant speak for my countrymen, most people rarely sit down to eat a loaf of bread.  Mustard, butter, cheeses, and other toppings can contribute to the salt intake as well as toppings and additions to the bread.  The bacon bread, salami bread, and goat cheese bread would all put the basic loaf well over the recommended guidelines before anything was added.  It bears remembering that too much salt may not affect the bulk ferment, but will retard the final rise and impede any oven spring.

**Comment by hendricius** [comment]
Maybe consider adding a PR with your comments? I think especially the note on salt + other ingredients. Goat cheese plus extra salt might be tricky. However - since I always add the goat cheese when shaping, it could be that gluten development will be less good?

**Comment by hendricius** [comment]
Closing for now. Thanks!
