### ISSUE TITLE
include support for preferment.

### ISSUE THREAD

**Issue by nimbius** [hendricius/the-bread-code#50]
Support in the basic loaf/somewhere for the inclusion of up to 40% preferment should be added, with appropriate math and explanation of the water discount for hydration of the final bread.  this could be extended into the sourdough recipe as a 250g sourdough starter would necessitate the same preferment math in the final rise to maintain proper hydration.

**Comment by hendricius** [comment]
Me gusta.

What about creating a recipe for the basic loaf + sour dough? Since the basic recipe was really only meant for yeast.

**Comment by nimbius** [comment]
Im a big fan of your sourdough tutorial as it doesnt regularly discard a portion of the sourdough starter.  My starter should be ready sometime next week, depending on the weather, so i can definitely send a pull request once the final loaf is baked.

**Comment by hendricius** [comment]
I'll close this for now, feel free to add the PR. Then we can open it again.
