### ISSUE TITLE
Missing .DLL

### ISSUE THREAD

**Issue by bvanvliet** [hendricius/the-bread-code#51]
Well, I've tried and failed to build the tasty breaded binaries three separate times now. With build number one, it only took out a couple of my cats and left an unpleasant odor on the furniture. The next two were very unusual, though. Try two resulted in _a lot_ of meth, and a _very_ aggressive visit from S.W.A.T -- and the third attempt resurrected Jesus. 

I suspect I have a missing or outdated .DLL somewhere. Thoughts?

**Comment by hendricius** [comment]
Please provide the DLL and then reopen this issue :D.
