### ISSUE TITLE
Am I missing something?

### ISSUE THREAD

**Issue by chaparin** [hendricius/the-bread-code#56]
How do you actually mix the starter with flour and water before baking? Is it 200 grams of starter with 150/150, or 300/300 grams flour water? How long do you mix? How long do you let it sit before baking? How long do you bake and at what temperature? I am probably just not using github correctly. Maybe the information is right in front of me?

**Comment by hendricius** [comment]
Hi. Good questions.

Does this help:
https://github.com/hendricius/the-bread-code/blob/master/basics/basic-sour-dough.md#preparation-steps

The other sourdough recipe you might have read was only about preparing the mother dough, not the actual baking. The link above is about the actual baking part.

Let me know if it is unclear, then I will update the article and add more detailed instructions.

Thanks for the feedback!

**Comment by chaparin** [comment]
I am all confused about proportions of flour, water, and starter. Also, the linked article uses one image 3 times. Not sure what happened there. :-(

**Comment by hendricius** [comment]
Oops. My bad. Nice catch.

Always feed your starter with same water and flour amounts. That's it. Feed it a little more than you actually need, because parts of it you want to return to the fridge.

**Comment by hendricius** [comment]
Hope this helps. Already fixed the images and will proceed now with making it a little easier to understand.

**Comment by chaparin** [comment]
Excellent, than you so much! I will look over the info, but I am so busy, I am sure just as you, unfortunately. I think I am going in with 300gm of starter, 225gm of flour and 225gm of flour. I will mix in an hour and then mix again in 8 hours and then bake in 10 hours after that. Will see what comes out. :-) Jazz is all about improvisation. :-D

**Comment by hendricius** [comment]
300 gram of starter in your bread means you should add 750 grams of flour to the bake. 300 is 40% of 750. That works as well. 21 grams of salt as well as 487,5 grams of water.

**Comment by chaparin** [comment]
Oh, I ended up with 550 / 550 grams of water and flour. I will see what comes out. But it's important to distinguish that the starter should make up 40% of flour to be added, not flour and water mixture. Also, thank you for clarifying that 65% (487,5) of total flour is water. I got a good rise this time, and instead of putting the starter away this time, I will mix another batch tonight.
