### ISSUE TITLE
Baking time rye sourdough

### ISSUE THREAD

**Issue by themmes** [hendricius/the-bread-code#68]
Despite preheating the oven to max temp (250C) and baking at 230C for 45 minutes, with an oven stone, the bread is not entirely done (a bit doughy/squashy in the core).

What are your experiences related to baking times for sourdough (or maybe rye specificly)?

**Comment by hendricius** [comment]
Very interesting. It just shows how different the ovens are in real life.

Do you by chance have a thermometer and could measure the temperature of your bread after 45 minutes? In my case they are usually ready at 95 degrees celsius. Maybe we should include that in the recipe as well?

Also it would be nice to conduct more research on temperatures in the final product.

**Comment by themmes** [comment]
Interesting! Thank you for you reply, I’ll experiment with the amount of water and waiting time after shaping.

**Comment by hendricius** [comment]
Had the same issue yesterday. I let the bread rest in the fridge overnight. It took longer for it to bake. Used thermometer and waited until 95 degrees. Then took it out.

**Comment by hendricius** [comment]
Closing it for now. Feel free to open again if still an issue.
