### ISSUE TITLE
Mold on sides of bowl used for mother dough

### ISSUE THREAD

**Issue by colinfike** [hendricius/the-bread-code#71]
Today is day 7 of my mother dough and I found dark grey mold/spores growing on the side of the bowl where some of the flour/water that got stuck on the sides during mixing dried. Just going to dump the entire batch and start over.

Is there something I did wrong to cause this? I used a big metal mixing bowl I had lying around. Should I have used a glass pitcher like in the sourdough instructions? It never indicated what type of bowl out side of a "big bowl" so I didn't think it mattered.

Thoughts?

**Comment by hendricius** [comment]
Thanks for posting. This should not have happened. How humid is the environment in which you built your mother dough? Do you have a place where it is not as humid? Secondly maybe try switching the bowl of your mother dough after 3 days to a new one. Just move all the mother dough to a new clean bowl.

Please let me know if that works. If yes, feel free to submit a pull request.

Happy Baking.

**Comment by nimbius** [comment]
@colinfike 
this seems normal.  I get this from time to time in my øland starter.  I just mix it into the rest of the starter before use.  ive even used dried/grey starter to build new starters.

**Comment by hendricius** [comment]
It seems to happen if you have too high heat in the initial steps. The moment you start having lactic bacteria you have an acidic environment that prevents the mold from appearing. You could also be unlucky, maybe the batch of grain used for the flour had a lot of mold initially.
