### ISSUE TITLE
Icon/Logo Design

### ISSUE THREAD

**Issue by Tobaloidee** [hendricius/the-bread-code#83]
Hi Sir @hendricius I am a graphic designer and I want to contribute by proposing an icon/logo design. As I've checked your great project, I thought that you might want one. If you are interested and wanna use it i will be gladly sending you the files as a gift for free. 

Here's my design Sir
- I created a minimal and clean design, You will notice it is a code symbol in which i incorporated the rolling pin at the middle for the idea of baking(bread). 

icon
![tbc](https://user-images.githubusercontent.com/36028424/39953137-778e6ae6-55d7-11e8-9fa8-19babd1c42be.png)

logotypes
![breadcode-02](https://user-images.githubusercontent.com/36028424/39953140-858d16c4-55d7-11e8-99f9-270b75f8d2f4.png)

![breadcode-03](https://user-images.githubusercontent.com/36028424/39953141-88f0790a-55d7-11e8-9ef7-95d013d390f7.png)

I hope you like and makes you wanna use it. Let me know you opinion or if you have suggestions Sir.

Thanks and best regards!

-Tobaloidee

**Comment by Tobaloidee** [comment]
I updated the colors with the reference that you send me thru email Sir @hendricius 

2 versions to choose from: Flat and Gradient

![offer](https://user-images.githubusercontent.com/36028424/39957025-3db97710-561e-11e8-99be-befa935b74f4.png)

**Comment by Tobaloidee** [comment]
Here's the final draft of our design Sir,

![all-10](https://user-images.githubusercontent.com/36028424/39959732-a8593216-5648-11e8-841e-f8b85ea55632.png)

and here is the link to my drive which includes all the needed files.
https://drive.google.com/drive/u/0/folders/1D8s_SUsJVv8SQz7IuFS3ujEqnKiC7MYg

Thanks so much and best regards!
-Tobaloidee

**Comment by hendricius** [comment]
Thanks. Merged it in the other pull request.
