### ISSUE TITLE
Structured data for the recipes?

### ISSUE THREAD

**Issue by locomo** [hendricius/the-bread-code#88]
Any thoughts on marking up the recipes with structured data? Have any schemas emerged as the de facto format for recipes online?

I found these for example:
https://developers.google.com/search/docs/data-types/recipe
http://schema.org/Recipe

**Comment by akx** [comment]
The schema.org/Recipe schema seems like a good start.

These could be marked up as YAML front-matter (or back-matter), or a fenced code block of YAML?

**Comment by hendricius** [comment]
I am closing this for now. I need to rethink the structure of the recipes - once that is done we can consider adding structured data. Thanks!
