### ISSUE TITLE
Basic dough questions / clarifications

### ISSUE THREAD

**Issue by davidmaitland** [hendricius/the-bread-code#89]
I'm trying the basic dough recipe, and I have a few questions:

> 5 grams of dry yeast or 1%

Is active dry yeast okay? I assume it doesn't need to be dissolved in water despite the packaging instructing to do so.

> Mix together all the ingredients listed by the recipe

The yeast is listed in the ingredients, so I added it in with the rest before going onto the _Add the yeast_ section 🤦‍♂️.

> Cover the dough with some foil or linen for 8 hours

Should the dough just be left on the side? Or somewhere warm / cool?

Thanks! 🍞

**Comment by davidmaitland** [comment]
Think I answered my own questions as it turned out okay.. A bit flat but it still tasted good.

I struggled with the dough not sticking to my hands / the board when shaping. Had to add a *lot* of extra flour to get it shaped.

![img_1793](https://user-images.githubusercontent.com/1108606/40199625-0593e800-5a12-11e8-93b3-f250767d7117.jpg)
![img_1797](https://user-images.githubusercontent.com/1108606/40199820-8bb49150-5a12-11e8-9698-2552a032033c.jpg)

**Comment by dimavs** [comment]
If dough is too watery on shaping stage it's better to use loaf tin or pan for baking rather than adding more flour at that stage.

**Comment by hendricius** [comment]
Well done. The bread looks really delicious!

I'm trying the basic dough recipe, and I have a few questions:

5 grams of dry yeast or 1%

-> You can use dry yeast as well as active yeast.

The yeast is listed in the ingredients, so I added it in with the rest before going onto the Add the yeast section 🤦‍♂️.

-> Good catch.

Should the dough just be left on the side? Or somewhere warm / cool?

-> Warm -> dough will rise more. Cold -> things are slower. Both is fine. I would suggest to experiment.

Thanks! 🍞
