### ISSUE TITLE
FAQ candidate: My sourdough has few bubbles

### ISSUE THREAD

**Issue by clehene** [hendricius/the-bread-code#94]
I've followed the sourdough recipe (https://github.com/hendricius/the-bread-code/blob/master/basics/sourdough.md) but after 7 days it only had a few bubbles (much (less <20 surface bubbles) than the one in the instruction picture). 

The sourdough smells a little sour and does taste sour, but it's unclear how sour it should be based on the "really sour" description in https://github.com/hendricius/the-bread-code/blob/master/basics/common-problems-faq.md#my-sourdough-already-looks-ready-after-4-days. I'd say mine is as sour as a medium-dry red wine (not sure what's the best comparison).

The temperature in my kitchen is between 20C (68F) and 22C (72F). The water I used every day should have had roughly the same (measured it once) as I used water from a Brita filter.

On the 8th day I mixed it and left it for another day hoping that it will get more bubbles, but to my surprise the next morning I had 1 1/2 bubbles :)

**Comment by hendricius** [comment]
Do you happen to have a picture? That would be helpful. Then we can work on resolving it :).

**Comment by hendricius** [comment]
This can depend on the flour that you use. Flour usually has yeast inside. You could consider using rye for a few days to feed your starter. Rye naturally has more yeast added. Definitely keep feeding your sourdough for a longer period of time, maybe once every 12 hours. That will make your dough really active.
