### ISSUE TITLE
Consider adding the Turkish Bread. 

### ISSUE THREAD

**Issue by kuharan** [hendricius/the-bread-code#95]
Check out this video - https://www.facebook.com/insiderpresents/videos/981149328703707/

**Comment by hendricius** [comment]
Wow. That looks amazing. Do you happen to have the recipe?

**Comment by kuharan** [comment]
Yes. I have the recipe.

**Comment by hendricius** [comment]
Can you add it?

**Comment by kuharan** [comment]
Like fork add the receipe and then merge?

**Comment by hendricius** [comment]
Yep.

**Comment by kuharan** [comment]
Alright. Gimme some time.

**Comment by hendricius** [comment]
Closing this for now - feel free to add it :)
