### ISSUE TITLE
Question: Type 550 vs. Type 405

### ISSUE THREAD

**Issue by majewsky** [hendricius/the-bread-code#97]
The two basic recipes (Basic Bread and Basic Sourdough Bread) both require "all-purpose flour. In Germany type 550." Since I only baked cakes and pastries before, I only have Type 405 in stock (the standard wheat flour that they sell at discounters). Would that be good as well, or should I use the next seven days (while I prepare the sourdough starter) to find somewhere that sells Type 550? Or, to be more precise: How would using Type 405 instead of Type 550 affect the dough and/or bread?

**Comment by hendricius** [comment]
Very good question. It would be an excellent experiment we can conduct. See https://github.com/hendricius/the-bread-code/pull/96. The gluten network will not be as strong as in 550. But you can bake a bread with it, do not worry. The bread will fall a part a little when cutting. From a health perspective the 550 has more nutrients than the 405. The higher the number the more ash remains when burning 100 grams of flour.

**Comment by majewsky** [comment]
Okay, I'll make my first loaf with 405 and (if I don't forget) post a picture here.
